Update backup.yml

diff --git a/.github/workflows/backup.yml b/.github/workflows/backup.yml
--- a/.github/workflows/backup.yml
+++ b/.github/workflows/backup.yml
@@ -44,7 +44,7 @@ jobs:
          echo "install=${{steps.install.conclusion}}" >> $GITHUB_OUTPUT
          echo "export=${{steps.export.conclusion}}" >> $GITHUB_OUTPUT
          echo "push=${{steps.push.conclusion}}" >> $GITHUB_OUTPUT
-         [ -f contentful/${env.export_date}/error.json ]  && echo "backup = failure" >> $GITHUB_OUTPUT || echo "backup = success" >> $GITHUB_OUTPUT      
+         [ -f contentful/${{env.export_date}}/error.json ]  && echo "backup = failure" >> $GITHUB_OUTPUT || echo "backup = success" >> $GITHUB_OUTPUT      
 
   send-email:
     if: ${{ always() }}
